### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by incub4t0r** [piekstra/tplink-cloud-api#12]
As of 18DEC2020, it seems importing `TPLinkDeviceManager` cannot be done through `tplink_cloud_api` as stated in the documentation. I was able to resolve this issue by using `from tplinkcloud import TPLinkDeviceManager` instead. 

Is this just an issue on my end?

**Comment by piekstra** [comment]
> As of 18DEC2020, it seems importing `TPLinkDeviceManager` cannot be done through `tplink_cloud_api` as stated in the documentation. I was able to resolve this issue by using `from tplinkcloud import TPLinkDeviceManager` instead.
> 
> Is this just an issue on my end?

It's possible the documentation is out of date. I expect your workaround is the correct solution. I will check and get back to you.

**Comment by piekstra** [comment]
@incub4t0r 
Great catch! It was definitely outdated documentation. Thank you for creating an issue to track it and get it resolved!

The fix is in this PR: https://github.com/piekstra/tplink-cloud-api/pull/13
