### ISSUE TITLE
How do I control individual plugs on a PowerStrip

### ISSUE THREAD

**Issue by zeetherocker** [piekstra/tplink-cloud-api#16]
I was wondering how I could control each of the different plugs available on my smart power strip. 
The examples don't show that. 
I tried to find all devices on my account. It lists the power strip but not the plugs themselves, so I could not create objects from the device_manager for the plugs. 
So I created an object for the plug. I can see the different children using get_sys_info function.  But unable to control them. The get_children() returns None and has_children() returns False

My power strip is KP303 with 3 plugs. 

Edit: After digging through the source, I see that my device is being recognized as an UNKNOWN type which is why I see the issue. My device name that's shown in find_devices is "TP-LINK_Power Strip_266A" and model name is "KP303"

I see now that this is not in the supported list. Sorry that was my bad. Can this be added to the list of supported devices?

**Comment by piekstra** [comment]
@zeetherocker Hi!

Thanks for doing the digging! It looks like the reason you can't control the device is indeed because it's not officially supported by the library yet. I can add that capability today but without a KP303 device of my own to test with there's not 100% guarantee it will work fully (I suspect you'll be able to control the plugs though).

**Comment by zeetherocker** [comment]
@piekstra Thank you for your reply! Much appreciated.

Last night I changed the source code a little bit, sort of a hack to get it working. I just made the KP303 be recognized as a HS300 object. Then just for testing, stored the children list from the async call on the device object and accessed these children using an index. 
This works for me now. Maybe if you add in the support, I can definitely test it for you. 

Also, how is the get_children() api supposed to be used

**Comment by piekstra** [comment]
@zeetherocker here is a pull request to add support for the KP303. If you could test that out with your devices before I merge it into the main branch that would be awesome! 

https://github.com/piekstra/tplink-cloud-api/pull/17

**Comment by piekstra** [comment]
@zeetherocker as to `get_children()` I think I may have messed that one up when I experimented with making things async. I will try and revert that now. You should be able to, once you have a device object like an HS300 device, call `get_children()` on it and have a list of objects for each of the children. Those you could then use functions like `power_on()` and `power_off()` for example.

**Comment by zeetherocker** [comment]
Awesome! Thank you so much @piekstra
Let me run some tests today and get back to you with the results

**Comment by piekstra** [comment]
> @piekstra Thank you for your reply! Much appreciated.
> 
> Last night I changed the source code a little bit, sort of a hack to get it working. I just made the KP303 be recognized as a HS300 object. Then just for testing, stored the children list from the async call on the device object and accessed these children using an index.
> This works for me now. Maybe if you add in the support, I can definitely test it for you.
> 
> Also, how is the get_children() api supposed to be used

Based on this I'm going to assume that the changes I made will function correctly and go ahead and merge the pull request and close this issue. Please feel free to reopen the issue if there's something wrong with the change!
