### ISSUE TITLE
More methods?

### ISSUE THREAD

**Issue by jake-rabbit** [piekstra/tplink-cloud-api#21]
There are a number of other useful functions it would be great to add, if possible?

Have prototyped these so far and they all work as expected:

    # Get SSID of network to which the device is connected
    def get_net_info(self):
        return self._pass_through_request('netif', 'get_stainfo', None)

    # Edit an existing rule (obtained via get_schedule_rules)
    def edit_schedule_rule(self, rule):
        return self._pass_through_request('schedule', 'edit_rule', rule)

    # Add a new rule
    def add_schedule_rule(self, rule):
        return self._pass_through_request('schedule', 'add_rule', rule)

    # Delete all currently scheduled rules
    def delete_all_scheduled_rules(self):
        return self._pass_through_request('schedule', 'delete_all_rules', None)

    # Delete a specific rule
    def delete_schedule_rule(self, rule_id):
        return self._pass_through_request('schedule', 'delete_rule', {'id': rule_id})

    # Get device timezone
    def get_timezone(self):
        return self._pass_through_request('time', 'get_timezone', {})

    # Get device current time
    def get_time(self):
        return self._pass_through_request('time', 'get_time', {})
`

Great work on this library, very much appreciated!

J

**Comment by piekstra** [comment]
@jake-rabbit These are excellent suggestions! I will try and add these in today after I give them a try.

**Comment by jake-rabbit** [comment]
Worth mentioning that for the rules you need a minimum set of fields declared or you'll get an error (code 3 I think) returned.
Managed to work out this set of entries in a rule is enough:

# Start options
sact:-1,  # start time active, -1 = disabled, 0 = turn off, 1 = turn on
smin:0,   # start time minute of day
stime_opt:-1, #  -1 or 0 = disabled, 1 = sunrise, 2 = sunset, soffset then relevant for 1 or 2
soffset:0,  # offset in mins from sunset/sunrise if stime_opt is 1 or 2
# End options
eact:-1,  # end time active, -1 = disabled, 0 = turn off, 1 = turn on
emin:0,   # end time minute of day
etime_opt:-1, #  -1 or 0 = disabled, 1 = sunrise, 2 = sunset, eoffset then relevant for 1 / 2
eoffset:0,  # offset in mins from sunset/sunrise if etime_opt is 1 or 2
# Misc
enable:1,  # if rule is enabled or not
repeat:1,  # if rule is repeated or single shot
wday:[1, 1, 1, 1, 1, 1, 1],  # days of week to run
name:'Schedule Rule'

Interestingly this means you can set up single rules programmatically that turn something on and off (or off and on), which you can't do via the app....
Most of the time you just use the sXXXX fields and not the eXXXX ones to replicate how the app works.

J

**Comment by SageCaleb** [comment]
@jake-rabbit just wanted to provide you with an update that I'm still working on this. I've started on it but it's a bit more complex than I originally thought and I would also like to automated tests for it. I don't have a lot of availability this weekend to work on it but will certainly see it through to completion :)

**Comment by piekstra** [comment]
@jake-rabbit just wanted to provide you with an update that I'm still working on this. I've started on it but it's a bit more complex than I originally thought and I would also like to automated tests for it. I don't have a lot of availability this weekend to work on it but will certainly see it through to completion :)

(posted with the wrong account earlier)

**Comment by piekstra** [comment]
@jake-rabbit still working on the last update to allow for schedule rule management. It's a big one and currently in-progress so stay tuned!

**Comment by jake-rabbit** [comment]
@piekstra that's amazing - thanks!  Looking forward to it.

**Comment by piekstra** [comment]
@jake-rabbit with v2.9.0 all of your requested functions have been released! Thanks again for your suggestions and hope it helps!
