### ISSUE TITLE
Version of requests package

### ISSUE THREAD

**Issue by CausticD** [piekstra/tplink-cloud-api#34]
Hi,

I am using this with OctoPi / OctoPrint which uses Python 3.7.3 and this works great. A minor note, you are explicitly requesting version 2.22.0 of the requests package. 2.25.1 is out and seems to work on both Ubuntu and Windows in my very limited testing. Is there a reason for this specific version? Are there known issues?

**Comment by piekstra** [comment]
@CausticD thanks for bringing this to my attention! I do believe there was a reason for it at one point but honestly cannot recall why. I will work on updating it to the latest version but will first be attempting to add Github Actions testing for other operating systems.

**Comment by CausticD** [comment]
@piekstra Thanks. Just wanted to find out if there was a hidden gotcha.

Great work BTW. Since my Smart Plugs don't work locally, using this is almost as good but also has some extra benefits, so all-in-all, love it.

**Comment by piekstra** [comment]
The library has been updated and is released with version 2.8.1 :)
