### ISSUE TITLE
Runtime API for KP115

### ISSUE THREAD

**Issue by net147** [piekstra/tplink-cloud-api#42]
It would be good if we could query the Runtime for KP115 as available through the Kasa app:

Today
- Current Runtime: x hours
- Total Runtime: x hours

Past 7 Days
- Daily Average: x hours
- Total Runtime: x hours

Past 30 days
- Daily Average: x hours
- Total Runtime: x hours

**Comment by piekstra** [comment]
@net147 this issue is resolved with the release of `v2.10.0` :) please refer to the release description for achieving the same data displayed in the Kasa app using the new methods.
