### ISSUE TITLE
HS100 does not support power usage?

### ISSUE THREAD

**Issue by abepetrillo** [piekstra/tplink-cloud-api#45]
I have the HS100 and the code suggests that this is a power usage device, and I dont think it is. I think this is causing a few issues when trying to get system information like the deviceMac. I'm very new to python so not sure how to fix yet. Just sharing my findings in case anyone else either hits the issue or knows how to fix it.

Also, when the device is unknown (I have P100s as well), the device info API is not consistent.
https://github.com/piekstra/tplink-cloud-api/blob/8fbe1bd309b18725a681110281ef6a052a2b52c8/tplinkcloud/device_info.py#L13
Here it is `device_name`, and for the HS100 it's `mac` https://github.com/piekstra/tplink-cloud-api/blob/8fbe1bd309b18725a681110281ef6a052a2b52c8/tplinkcloud/hs100.py#L19

**Comment by piekstra** [comment]
@abepetrillo thanks for posting your findings! I will do my best to investigate these this week and let you know what I uncover as well as create any necessary pull requests.

**Comment by piekstra** [comment]
@abepetrillo on the power part you are entirely correct - looks like it was an oversight on my part. According to the Kasa specifications there is no support for the power usage functionality: https://www.kasasmart.com/us/products/smart-plugs/kasa-smart-wifi-plug-hs100

I will add that fix soon.

As for the inconsistencies, `device_info` is something that all devices have, unknown or not, but any time a device type is unknown there's a possibility that none of the library's features will work for it, including the parts of `device_info` that the library assumes all devices will have. The primary intent behind the unknown type is to prevent certain calls from breaking when unknown (currently unsupported) devices are found associated with your account. Secondarily, it can allow for _potential_ usage of those devices. Realistically, those unknown devices can't reliably be interacted with using this library until support for them is added officially. `sys_info` is distinctly different though generally has a lot of overlapping data. `sys_info` is sourced using a specific API request for `system` data using `get_sysinfo`. In contrast, the `device_info` comes back with each device found associated with your account when requesting the list of your devices.

**Comment by piekstra** [comment]
@abepetrillo the HS100 power usage bug has been addressed with the release of `v2.10.1` :)
