### ISSUE TITLE
HS110/Emeter not working, wrong variable name

### ISSUE THREAD

**Issue by ShayBox** [piekstra/tplink-cloud-api#51]
Have you tested emeter on any devices? On my HS110 the response variables don't have `_wh` so it's not reading them right, Is this the case with some devices or has emeter never been tested.

EDIT: Seems the summary classes are kinda useless anyway, would you accept a pr to just remove these classes and return the raw data like how the nodejs library does it, or do you want to check for both variable names

**Comment by piekstra** [comment]
@ShayBox I've tested emeter capabilities on `HS300` devices and have the data retrieved successfully. It's possible that the `HS100` follows a different contract and has different names in the response - I will investigate that and make adjustments accordingly.

Regarding the summary classes, returning raw JSON does not inform the end user of the library what to expect in a response. It also does not provide the same level of type safety as when using the provided classes. This was a decision I made early on to allow for friendlier usage of the API. I've considered creating and exposing separate methods that return raw data, and will set aside some time to do so if you would find it helpful.

**Comment by ShayBox** [comment]
The hs110 seems to return suffixed variable names

**Comment by piekstra** [comment]
As an update, I have not had a chance to look at this yet. I do have an `HS110` available to debug and fix the issue when I can get around to it.

**Comment by piekstra** [comment]
I have not forgotten about this! Hoping to spend time on it today.
