### ISSUE TITLE
Making the library fully async?

### ISSUE THREAD

**Issue by thisiscam** [piekstra/tplink-cloud-api#52]
Hi,

Would it make sense to make the library completely async? This will solve the problem of #50.

Essentially, IMO the problem is that calling `asyncio.run` in a library is not a very elegant solution since it interferes with other libraries that also uses `asyncio`. The [Python doc](https://docs.python.org/3/library/asyncio-task.html#asyncio.run) says::
> This function always creates a new event loop and closes it at the end. It should be used as a main entry point for asyncio programs, and should ideally only be called once.

**Comment by piekstra** [comment]
Thanks for the contribution! I appreciate your solution to this problem.

**Comment by piekstra** [comment]
This is published and available :)

https://github.com/piekstra/tplink-cloud-api/releases/tag/v4.0.0
