### ISSUE TITLE
Unable to Login after enabling 2FA

### ISSUE THREAD

**Issue by DkGnjCfEcA** [piekstra/tplink-cloud-api#69]
TP Link introduced 2FA authentication with latest app update, and unfortunately the app is broken to turn-off the 2FA.
Is there a way to add to login using 2FA?

**Comment by webbpage** [comment]
I'm having the same issue.

**Comment by piekstra** [comment]
That's unfortunate. I will need to investigate to see what can be done to programmatically handle 2FA. It's possible they've effectively bricked any programmatic access of their API.

**Comment by webbpage** [comment]
The API seems to be working as normal as long as 2FA is not enabled.

**Comment by DkGnjCfEcA** [comment]
> That's unfortunate. I will need to investigate to see what can be done to programmatically handle 2FA. It's possible they've effectively bricked any programmatic access of their API.

thanks, is there is a API documentation link, I can probably poke around and see if they have updated their api documentation on how to handle it.

**Comment by DkGnjCfEcA** [comment]
App got updated to turn off the 2FA, so at least I can continue using these APIs.
